version: "3.8"

services:
  mongodb:
    image: mongo:7.0
    container_name: local-mongodb
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: lms
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all"]
    volumes:
      - mongodb_data:/data/db
    networks: 
      - lms-network
networks:
  lms-network:
    driver:  bridge

volumes:
  mongodb_data: